{
  "_url": "https://github.com/PowerShell/PowerShell/issues/16287",
  "author": "bender-the-greatest",
  "body": "### Prerequisites\n\n- [x] Write a descriptive title.\n- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)\n- [X] Search the existing issues.\n- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).\n- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).\n\n### Steps to reproduce\n\nUncaught terminating errors are swallowed when they occur in a `try/finally` block arrangement when there is no `catch` block defined. This behavior differs from that in PowerShell 5.1, and is not mentioned in the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md#why-didnt-an-error-throw-an-exception) section regarding errors.\r\n\r\nIt is also not mentioned from what I could tell when searching for the words `try`, `finally`, or `catch` in the [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell) article. I could also not find any issues describing this behavior after a quick search, so I assume this is a bug.\n\n### Expected behavior\n\n```console\nFunction Test-Error {\r\n  try {\r\n    throw \"I am Error.\"\r\n  } finally {\r\n    Write-Host 'Function ended'\r\n  }\r\n}\r\n\r\nTest-Error\r\n\r\n\r\nExpected output:\r\n\r\n> function ended\r\nI am error\r\nAt line:2 char:7\r\n+  try {throw \"I am error\"}finally{write-host 'function ended'}\r\n+       ~~~~~~~~~~~~~~~~~~\r\n    + CategoryInfo          : OperationStopped: (I am error:String) [], RuntimeException\r\n    + FullyQualifiedErrorId : I am error\n```\n\n\n### Actual behavior\n\n```console\nSame code as in the expected behavior, but there is no output, and the `$Error` variable is not populated with this information.\n```\n\n\n### Error details\n\n_No response_\n\n### Environment data\n\n```powershell\nName                           Value\r\n----                           -----\r\nPSVersion                      7.1.5\r\nPSEdition                      Core\r\nGitCommitId                    7.1.5\r\nOS                             Microsoft Windows 10.0.19042\r\nPlatform                       Win32NT\r\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0\u2026}\r\nPSRemotingProtocolVersion      2.3\r\nSerializationVersion           1.1.0.1\r\nWSManStackVersion              3.0\n```\n\n\n### Visuals\n\n_No response_",
  "closed_at": "2021-10-21T16:59:53Z",
  "comments": [
    {
      "author": "bender-the-greatest",
      "author_association": "NONE",
      "body": "I goofed. This is not a bug.",
      "created_at": "2021-10-21T16:59:53Z",
      "updated_at": "2021-10-21T16:59:53Z"
    }
  ],
  "created_at": "2021-10-21T16:45:41Z",
  "labels": [],
  "number": 16287,
  "state": "closed",
  "title": "Using try/finally without a catch swallows any unhandled errors, and does not emit information to the error stream or $Error variable",
  "updated_at": "2021-10-21T17:05:00Z"
}