{
  "_url": "https://github.com/PowerShell/PowerShell/issues/17682",
  "author": "leonardder",
  "body": "### Prerequisites\r\n\r\n- [X] Write a descriptive title.\r\n- [X] Make sure you are able to repro it on the [latest released version](https://github.com/PowerShell/PowerShell/releases)\r\n- [X] Search the existing issues.\r\n- [X] Refer to the [FAQ](https://github.com/PowerShell/PowerShell/blob/master/docs/FAQ.md).\r\n- [X] Refer to [Differences between Windows PowerShell 5.1 and PowerShell](https://docs.microsoft.com/powershell/scripting/whats-new/differences-from-windows-powershell).\r\n\r\n### Steps to reproduce\r\n1. Download the following project: [psTest_remote_runspace.zip](https://github.com/PowerShell/PowerShell/files/9112153/psTest_remote_runspace.zip)\r\n2. Execute it\r\n\r\n### Expected behavior\r\nOutput:\r\n```console\r\none\r\ntwo\r\nthree\r\n```\r\n\r\nThis output is generated when using System.Management.Automation 7.0.*\r\n\r\n### Actual behavior\r\nOutput:\r\n\r\n```console\r\none\r\nUnhandled exception. System.Management.Automation.Runspaces.InvalidRunspaceStateException: The runspace state is not valid for this operation.\r\n ---> System.Management.Automation.Runspaces.InvalidRunspacePoolStateException: Cannot perform the operation because the runspace pool is not in the 'Opened' state. The current state is 'Broken'.\r\n   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.AssertPoolIsOpen()\r\n   at System.Management.Automation.Runspaces.RunspacePool.AssertPoolIsOpen()\r\n   at System.Management.Automation.PowerShell.CoreInvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state, PSDataCollection`1 asyncResultOutput)\r\n   --- End of inner exception stack trace ---\r\n   at System.Management.Automation.PowerShell.CoreInvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state, PSDataCollection`1 asyncResultOutput)\r\n   at System.Management.Automation.PowerShell.BeginInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings, AsyncCallback callback, Object state)\r\n   at System.Management.Automation.PowerShell.BeginInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output)\r\n   at System.Management.Automation.PowerShell.InvokeAsync[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output)\r\n   at Program.RunPowerShell(PowerShellProcessInstance instance, String message) in D:\\psTest_remote_runspace\\Program.cs:line 23\r\n   at Program.Main(String[] args) in D:\\psTest_remote_runspace\\Program.cs:line 39\r\n   at Program.<Main>(String[] args)\r\n```\r\n\r\nAlternative output:\r\n\r\n```console\r\none\r\nUnhandled exception. System.Management.Automation.Remoting.PSRemotingTransportException: There is an error processing data from the background process. Error reported: UPlN5c3RlbS5NYW5hZ2VtZW50LkF1dG9tYXRpb24uUFNQcmltaXRpdmVEaWN0aW9uYXJ5PC9UPjxUPlN5c3RlbS5Db2xsZWN0aW9ucy5IYXNodGFibGU8L1Q+PFQ+U3lzdGVtLk9iamVjdDwvVD48L1ROPjxEQ1Q+PEVuPjxTIE49IktleSI+QnJlYWtBbGw8L1M+PEIgTj0iVmFsdWUiPmZhbHNlPC9CPjwvRW4+PEVuPjxTIE49IktleSI+RGV<Data Stream='Default' PSGuid='00000000-0000-0000-0000-000000000000'>AAAAAAAAAAoAAAAAAAAAAAMAAABnAQAAAAUQAgDZ5A0ndChcQryGVexra4VDAAAAAAAAAAAAAAAAAAAAAO+7vzxPYmogUmVmSWQ9IjAiPjxNUz48STMyIE49IlJ1bnNwYWNlU3RhdGUiPjI8L0kzMj48L01TPjwvT2JqPg==</Data>.\r\n   at System.Management.Automation.Runspaces.AsyncResult.EndInvoke()\r\n   at System.Management.Automation.Runspaces.Internal.RunspacePoolInternal.EndOpen(IAsyncResult asyncResult)\r\n   at System.Management.Automation.Runspaces.Internal.RemoteRunspacePoolInternal.Open()\r\n   at System.Management.Automation.Runspaces.RunspacePool.Open()\r\n   at System.Management.Automation.RemoteRunspace.Open()\r\n   at Program.RunPowerShell(PowerShellProcessInstance instance, String message) in D:\\psTest_remote_runspace\\Program.cs:line 12\r\n   at Program.Main(String[] args) in D:\\psTest_remote_runspace\\Program.cs:line 39\r\n   at Program.<Main>(String[] args)`\r\n```\r\n\r\n### Environment data\r\n\r\n```powershell\r\nPSVersion                      5.1.22000.653                                                                            \r\nPSEdition                      Desktop                                                                                  \r\nPSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                                                  \r\nBuildVersion                   10.0.22000.653                                                                           \r\nCLRVersion                     4.0.30319.42000                                                                          \r\nWSManStackVersion              3.0                                                                                      \r\nPSRemotingProtocolVersion      2.3                                                                                      \r\nSerializationVersion           1.1.0.1\r\n```\r\n\r\n",
  "closed_at": null,
  "comments": [
    {
      "author": "leonardder",
      "author_association": "NONE",
      "body": "I was able to pinpoint the bug somewhere between 7.1.0.Preview.1 and 7.1.0.Preview.2. Starting from 7.1.0.preview.2 and onwards, this problem occurs.",
      "created_at": "2022-07-14T14:54:45Z",
      "updated_at": "2022-07-14T14:54:45Z"
    }
  ],
  "created_at": "2022-07-14T13:34:41Z",
  "labels": [
    "WG-Engine",
    "Needs-Triage"
  ],
  "number": 17682,
  "state": "open",
  "title": "Can't start multiple out of process runspaces with System.Management.Automation 7.1.preview.2 and beyond",
  "updated_at": "2022-07-15T03:25:24Z"
}